[project]
name = "terdo"
version = "0.1.0"
description = "A terminal todo app!"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "textual[syntax]>=2.1.2",
    "pydantic>=2.10.6",
]

[dependency-groups]
dev = [
    "ruff>=0.11.0",
    "textual-dev>=1.7.0",
]
