[project]
name = "terdo"
version = "0.1.0"
description = "A terminal todo app!"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "textual-dev>=1.7.0",
    "textual[syntax]>=2.1.2",
    "pydantic>=2.10.6",
    "ruff>=0.9.9",
]